# This file is part of DTE-ERAU. Copyright 2023 Embry-Riddle Aeronautical University
#
# DTE-ERAU is free software: you can redistribute it and/or modify it under the terms of the GNU 
# General Public License as published by the Free Software Foundation, either version 3 of the License, or 
# (at your option) any later version.
#
# DTE-ERAU is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without 
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with DTE-ERAU. If not, see 
# <https://www.gnu.org/licenses/>. 

serve:
  proxy:
    port: 4455
  api:
    port: 4456

access_rules:
  repositories:
    - file:///config/rules.yaml
  matching_strategy: regexp

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

mutators:
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://pdp:9990/auth
      payload: |
        {
          "resource_group": "web",
          "resource": "{{ printIndex .MatchContext.RegexpCaptureGroups 1 }}",
          "user": "{{ .MatchContext.Header.Get "x-goog-authenticated-user-id" }}"
        }

authenticators:
  noop:
    enabled: true
